export const GET_CHARACTERS = 'GET_CHARACTERS';
export const CHARACTER_DETAIL = 'CHARACTER_DETAIL';
export const CLEAN_DETAIL = 'CLEAN_DETAIL';
export const SAVE_CHARACTERS = 'SAVE_CHARACTERS';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';